### ISSUE TITLE
Vuepress integration?

### ISSUE THREAD

**Issue by douglasg14b** [voraciousdev/vue-markdown-editor#9]
I've been looking for a way to live-edit Vuepress docs, so changing & managing docs is less of a burden. I stumbled upon this project which, at first glance, seems like something that may be a significant step towards that.

My objectives are:
* Be able to edit any Vuepress doc with a themed markdown editor
* Be able to fully preview the changes (The way your editor renders the markdown is 10/10 for editing, but a full render is still very necessary)

You're more of an expert than me in this area, so I want your opinion!

**Questions for you:**

1. Can the editor be themed to match Vuepress, if so, do you have guidance there?
2. What pitfalls & hurdles do you see if I wanted to attempt to integrate this markdown editor into Vuepress?
3. Do you have any advice?
4. Would it be better to look at Octo instead to see what direction I need to head?

**Comment by douglasg14b** [comment]
Some more research indicates that https://github.com/writewithocto/ink may be more relevant?

In which case, same questions apply!

**Comment by davidmyersdev** [comment]
Hey @douglasg14b. [Ink](https://github.com/writewithocto/ink) is definitely the package you are looking for. It is the successor to this package, and it has theme customization (which it sounds like you need). As for rich previews, that is a feature I would need to add, but it's not out of the question.

**Comment by davidmyersdev** [comment]
I'm closing this issue now that this project has been fully replaced by the new Ink implementation.
